import { Color } from "./Color";
import { EggGroup } from "./EggGroup";
import { EvolutionChain } from "./EvolutionChain";
import { EvolvesFromSpecies } from "./EvolvesFromSpecies";
import { FlavorTextEntry } from "./FlavorText";
import { Genera } from "./Genera";
import { Generation } from "./Generation";
import { GrowthRate } from "./GrowthRate";
import { Habitat } from "./Habitat";
import { Name } from "./Name";
import { PalParkEncounter } from "./PalParkEncounter";
import { PokedexNumber } from "./PokedexNumber";
import { Shape } from "./Shape";
import { Variety } from "./Variety";

export interface Specie {
  base_happiness: number;
  capture_rate: number;
  color: Color;
  egg_groups: EggGroup[];
  evolution_chain: EvolutionChain;
  evolves_from_species: EvolvesFromSpecies;
  flavor_text_entries: FlavorTextEntry[];
  form_descriptions: any[];
  forms_switchable: boolean;
  gender_rate: number;
  genera: Genera[];
  generation: Generation;
  growth_rate: GrowthRate;
  habitat: Habitat;
  has_gender_differences: boolean;
  hatch_counter: number;
  id: number;
  is_baby: boolean;
  is_legendary: boolean;
  is_mythical: boolean;
  name: string;
  names: Name[];
  order: number;
  pal_park_encounters: PalParkEncounter[];
  pokedex_numbers: PokedexNumber[];
  shape: Shape;
  varieties: Variety[];
}
